modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mineon"
version="1.0.0"
displayName="Mineon"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="dz, MCreator"

[[dependencies.mineon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




